name: task_manager
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  uuid: ^4.5.1
  shared_preferences: ^2.5.2
  dartz: ^0.10.1
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  badges: ^3.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
